apiVersion: v1
kind: ConfigMap
metadata:
  name: emplus-api-config
  namespace: emplus-local
data:
  DATA_STORE: postgres
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/emplus
  READ_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/emplus
  REDIS_URL: redis://redis:6379
  MAIL_HOST: mailpit
  MAIL_PORT: "1025"
  MAIL_FROM: no-reply@emplus.local
  MINIO_ENDPOINT: http://minio:9000
  MINIO_REGION: us-east-1
  MINIO_BUCKET: emplus
  MINIO_USE_SSL: "false"
  SWAGGER_ENABLED: "true"
  SWAGGER_PATH: /v1/docs
  ALLOW_MOCK_OAUTH: "false"
  NODE_ENV: development
  PORT: "3000"
