apiVersion: v1
kind: Secret
metadata:
  name: emplus-secrets
  namespace: emplus-local
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: emplus
  MINIO_ROOT_USER: emplus_local_admin
  MINIO_ROOT_PASSWORD: emplus-local-minio-2026
  MINIO_ACCESS_KEY: emplus_local_admin
  MINIO_SECRET_KEY: emplus-local-minio-2026
