import type { GiftSuggestion } from "../types.ts";

const placeholder = (id: string) => `https://example.com/emplus-gifts/${id}`;

export const giftSuggestionsConfig: GiftSuggestion[] = [
  {
    id: "anniversary-memory-box",
    title: "Hộp kỷ niệm mini",
    description: "Một hộp nhỏ để cất vé xem phim, ảnh in và vài mẩu giấy nhắn của hai người.",
    category: "ANNIVERSARY",
    budgetRange: "FROM_100K_TO_300K",
    platforms: ["SHOPEE", "OTHER"],
    url: placeholder("anniversary-memory-box"),
    tags: ["anniversary", "memory", "photo", "ke-niem"],
    suitableFor: ["100 ngày", "1 năm", "cột mốc quan trọng"],
  },
  {
    id: "anniversary-photo-album",
    title: "Album ảnh cầm tay",
    description: "Album ảnh nhỏ gọn để lưu những khoảnh khắc đáng nhớ nhất.",
    category: "ANNIVERSARY",
    budgetRange: "FROM_100K_TO_300K",
    platforms: ["SHOPEE", "OTHER"],
    url: placeholder("anniversary-photo-album"),
    tags: ["anniversary", "photo", "memory", "album"],
    suitableFor: ["365 ngày", "500 ngày", "timeline memories"],
  },
  {
    id: "anniversary-custom-calendar",
    title: "Lịch để bàn in ngày yêu",
    description: "Lịch để bàn có thể đánh dấu ngày bắt đầu yêu và các cột mốc riêng.",
    category: "ANNIVERSARY",
    budgetRange: "FROM_300K_TO_700K",
    platforms: ["SHOPEE", "OTHER"],
    url: placeholder("anniversary-custom-calendar"),
    tags: ["anniversary", "date", "calendar", "custom"],
    suitableFor: ["ngày yêu", "kỷ niệm năm", "cột mốc tự tạo"],
  },
  {
    id: "couple-bracelet-simple",
    title: "Vòng tay đôi tối giản",
    description: "Vòng tay đôi nhẹ nhàng, dễ đeo hằng ngày, không quá phô trương.",
    category: "COUPLE_ITEM",
    budgetRange: "FROM_100K_TO_300K",
    platforms: ["TIKTOK", "SHOPEE"],
    url: placeholder("couple-bracelet-simple"),
    tags: ["couple", "daily", "anniversary", "matching"],
    suitableFor: ["100 ngày", "200 ngày", "random surprise"],
  },
  {
    id: "couple-keychain",
    title: "Móc khóa đôi khắc tên",
    description: "Một món nhỏ nhưng dùng được mỗi ngày, hợp với các dịp bất ngờ.",
    category: "COUPLE_ITEM",
    budgetRange: "UNDER_100K",
    platforms: ["SHOPEE"],
    url: placeholder("couple-keychain"),
    tags: ["couple", "name", "small", "daily"],
    suitableFor: ["bất ngờ nhỏ", "cột mốc nhẹ"],
  },
  {
    id: "couple-mug-set",
    title: "Cặp ly uống nước đôi",
    description: "Hai chiếc ly đồng bộ cho những buổi sáng hoặc tối gọi video cùng nhau.",
    category: "COUPLE_ITEM",
    budgetRange: "FROM_100K_TO_300K",
    platforms: ["SHOPEE", "OTHER"],
    url: placeholder("couple-mug-set"),
    tags: ["couple", "home", "daily", "warm"],
    suitableFor: ["ở nhà", "kỷ niệm tháng", "bất ngờ nhẹ"],
  },
  {
    id: "handmade-love-letter-kit",
    title: "Bộ viết thư tay",
    description: "Giấy, phong bì và sticker để viết một lá thư thật riêng.",
    category: "HANDMADE",
    budgetRange: "UNDER_100K",
    platforms: ["SHOPEE", "OTHER"],
    url: placeholder("handmade-love-letter-kit"),
    tags: ["handmade", "letter", "apology", "anniversary"],
    suitableFor: ["làm hòa", "kỷ niệm", "ngày bình thường"],
  },
  {
    id: "handmade-scrapbook-kit",
    title: "Bộ làm scrapbook",
    description: "Giấy trang trí, sticker và băng keo để tự làm sổ kỷ niệm.",
    category: "HANDMADE",
    budgetRange: "FROM_100K_TO_300K",
    platforms: ["TIKTOK", "SHOPEE"],
    url: placeholder("handmade-scrapbook-kit"),
    tags: ["handmade", "memory", "photo", "anniversary"],
    suitableFor: ["365 ngày", "1000 ngày", "timeline memories"],
  },
  {
    id: "apology-flower-mini",
    title: "Bó hoa mini xin lỗi",
    description: "Một bó hoa nhỏ kèm lời nhắn ngắn để mở đầu cuộc nói chuyện dịu hơn.",
    category: "APOLOGY",
    budgetRange: "FROM_100K_TO_300K",
    platforms: ["OTHER"],
    url: placeholder("apology-flower-mini"),
    tags: ["apology", "flower", "make-up", "soft"],
    suitableFor: ["làm hòa", "sau khi dỗi", "ngày cần dịu lại"],
  },
  {
    id: "apology-snack-box",
    title: "Hộp snack làm hòa",
    description: "Một hộp đồ ăn vặt dễ thương để gửi lời xin lỗi bớt căng thẳng.",
    category: "APOLOGY",
    budgetRange: "UNDER_100K",
    platforms: ["SHOPEE", "OTHER"],
    url: placeholder("apology-snack-box"),
    tags: ["apology", "snack", "food", "make-up"],
    suitableFor: ["làm hòa", "dỗi nhẹ", "rủ đi ăn"],
  },
  {
    id: "birthday-cake-mini",
    title: "Bánh sinh nhật mini",
    description: "Bánh nhỏ đủ xinh cho một buổi chúc mừng riêng tư.",
    category: "BIRTHDAY",
    budgetRange: "FROM_100K_TO_300K",
    platforms: ["OTHER"],
    url: placeholder("birthday-cake-mini"),
    tags: ["birthday", "cake", "sweet", "surprise"],
    suitableFor: ["sinh nhật", "bất ngờ trong ngày"],
  },
  {
    id: "birthday-perfume-travel",
    title: "Nước hoa mini size",
    description: "Món quà gọn, tinh tế, hợp nếu đã biết mùi người ấy thích.",
    category: "BIRTHDAY",
    budgetRange: "FROM_300K_TO_700K",
    platforms: ["TIKTOK", "SHOPEE", "OTHER"],
    url: placeholder("birthday-perfume-travel"),
    tags: ["birthday", "premium", "personal", "scent"],
    suitableFor: ["sinh nhật", "dịp đặc biệt"],
  },
  {
    id: "random-coffee-voucher",
    title: "Voucher cà phê cuối tuần",
    description: "Một lời rủ đơn giản cho buổi hẹn cuối tuần gần nhất.",
    category: "RANDOM_SURPRISE",
    budgetRange: "UNDER_100K",
    platforms: ["OTHER"],
    url: placeholder("random-coffee-voucher"),
    tags: ["random", "date", "coffee", "weekend"],
    suitableFor: ["bất ngờ nhỏ", "rủ đi chơi", "ngày thường"],
  },
  {
    id: "random-plushie-small",
    title: "Gấu bông nhỏ để bàn",
    description: "Một món mềm mại để người ấy đặt ở bàn học hoặc bàn làm việc.",
    category: "RANDOM_SURPRISE",
    budgetRange: "FROM_100K_TO_300K",
    platforms: ["TIKTOK", "SHOPEE"],
    url: placeholder("random-plushie-small"),
    tags: ["random", "cute", "desk", "soft"],
    suitableFor: ["nhớ người ấy", "bất ngờ nhỏ"],
  },
  {
    id: "anniversary-star-map",
    title: "Tranh bản đồ sao ngày yêu",
    description: "Một bức tranh cá nhân hóa theo ngày bắt đầu yêu hoặc ngày kỷ niệm.",
    category: "ANNIVERSARY",
    budgetRange: "FROM_300K_TO_700K",
    platforms: ["SHOPEE", "OTHER"],
    url: placeholder("anniversary-star-map"),
    tags: ["anniversary", "custom", "date", "decor"],
    suitableFor: ["1 năm", "ngày yêu", "cột mốc quan trọng"],
  },
  {
    id: "couple-phonecase",
    title: "Ốp điện thoại đôi",
    description: "Ốp đôi cùng style, dễ thay và hợp với cặp đôi thích đồ đồng bộ.",
    category: "COUPLE_ITEM",
    budgetRange: "FROM_100K_TO_300K",
    platforms: ["TIKTOK", "SHOPEE"],
    url: placeholder("couple-phonecase"),
    tags: ["couple", "matching", "daily", "phone"],
    suitableFor: ["bất ngờ", "cột mốc nhẹ"],
  },
  {
    id: "handmade-coupon-book",
    title: "Sổ coupon tự làm",
    description: "Một cuốn coupon nhỏ như một bữa ăn, một cuộc gọi dài, một buổi đi dạo.",
    category: "HANDMADE",
    budgetRange: "UNDER_100K",
    platforms: ["OTHER"],
    url: placeholder("handmade-coupon-book"),
    tags: ["handmade", "date", "care", "random"],
    suitableFor: ["ngày thường", "làm hòa", "bất ngờ"],
  },
  {
    id: "birthday-book-with-note",
    title: "Một cuốn sách kèm lời nhắn",
    description: "Chọn một cuốn sách hợp gu và viết lời nhắn ở trang đầu.",
    category: "BIRTHDAY",
    budgetRange: "FROM_100K_TO_300K",
    platforms: ["SHOPEE", "OTHER"],
    url: placeholder("birthday-book-with-note"),
    tags: ["birthday", "book", "letter", "personal"],
    suitableFor: ["sinh nhật", "người thích đọc"],
  },
  {
    id: "random-movie-night-kit",
    title: "Set xem phim tại nhà",
    description: "Snack, nước uống và một tấm thiệp mời xem phim cùng nhau.",
    category: "RANDOM_SURPRISE",
    budgetRange: "FROM_100K_TO_300K",
    platforms: ["SHOPEE", "OTHER"],
    url: placeholder("random-movie-night-kit"),
    tags: ["random", "date", "movie", "home"],
    suitableFor: ["cuối tuần", "hẹn tại nhà", "timeline memory"],
  },
  {
    id: "anniversary-premium-dinner",
    title: "Bữa tối kỷ niệm",
    description: "Một buổi tối được đặt trước, hợp với các cột mốc lớn.",
    category: "ANNIVERSARY",
    budgetRange: "ABOVE_700K",
    platforms: ["OTHER"],
    url: placeholder("anniversary-premium-dinner"),
    tags: ["anniversary", "date", "food", "premium"],
    suitableFor: ["1 năm", "2 năm", "1000 ngày"],
  },
  {
    id: "apology-dessert-delivery",
    title: "Một phần dessert gửi tận nơi",
    description: "Một món ngọt nhỏ để bắt đầu lời xin lỗi bằng cảm giác dễ chịu hơn.",
    category: "APOLOGY",
    budgetRange: "FROM_100K_TO_300K",
    platforms: ["OTHER"],
    url: placeholder("apology-dessert-delivery"),
    tags: ["apology", "sweet", "food", "make-up"],
    suitableFor: ["làm hòa", "dỗ người ấy"],
  },
  {
    id: "couple-ring-simple",
    title: "Nhẫn đôi đơn giản",
    description: "Nhẫn đôi tối giản cho cặp đôi thích giữ một dấu hiệu nhỏ bên mình.",
    category: "COUPLE_ITEM",
    budgetRange: "FROM_300K_TO_700K",
    platforms: ["TIKTOK", "SHOPEE"],
    url: placeholder("couple-ring-simple"),
    tags: ["couple", "matching", "anniversary", "ring"],
    suitableFor: ["365 ngày", "kỷ niệm lớn", "cột mốc quan trọng"],
  },
];
