apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: emplus-staging

resources:
  - ../../base
  - namespace.yaml
  - configmap.yaml

images:
  - name: ghcr.io/OWNER/emplus-api
    newName: ghcr.io/OWNER/emplus-api
    newTag: REPLACE_ME

patches:
  - path: ingress.patch.yaml

