'use client';

import { useMemo, useState } from 'react';
import { useBuilderStore } from '@/store/builder-store';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Download, Copy, Check, X } from 'lucide-react';
import { toast } from 'sonner';
import { ScrollArea } from '@/components/ui/scroll-area';

interface ExportDialogProps {
  onClose: () => void;
}

export function ExportDialog({ onClose }: ExportDialogProps) {
  const { config } = useBuilderStore();
  const [copiedFile, setCopiedFile] = useState<string | null>(null);

  const tokensExport = useMemo(() => {
    return `/**
 * Design Tokens - Auto-generated by Design Builder
 * Last updated: ${config.metadata.lastUpdated}
 */

import type { Tokens } from './types';

export const tokens: Tokens = ${JSON.stringify(config.tokens, null, 2)};
`;
  }, [config.tokens, config.metadata.lastUpdated]);

  const themesExport = useMemo(() => {
    return `/**
 * Theme Definitions - Auto-generated by Design Builder
 * Last updated: ${config.metadata.lastUpdated}
 */

import type { Themes } from './types';

export const themes: Themes = ${JSON.stringify(config.themes, null, 2)};
`;
  }, [config.themes, config.metadata.lastUpdated]);

  const handleCopy = (text: string, file: string) => {
    navigator.clipboard.writeText(text);
    setCopiedFile(file);
    toast.success('Copied!');
    setTimeout(() => setCopiedFile(null), 2000);
  };

  const handleDownload = (content: string, filename: string) => {
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success(`Downloaded ${filename}`);
  };

  return (
    <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-50 p-4 backdrop-blur-sm">
      <div className="bg-background rounded-lg shadow-2xl max-w-4xl w-full max-h-[90vh] overflow-hidden flex flex-col border border-border">
        <div className="p-6 border-b flex items-center justify-between shrink-0 bg-muted/30">
          <h2 className="text-xl font-bold">Export Design Tokens</h2>
          <Button 
            variant="ghost" 
            size="icon" 
            onClick={onClose}
            className="hover:bg-secondary transition-colors"
          >
            <X className="w-5 h-5" />
          </Button>
        </div>

        <ScrollArea className="flex-1 p-6">
          <div className="space-y-6">
            {/* Metadata */}
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-semibold">Metadata</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <Label className="text-muted-foreground text-xs">Name</Label>
                    <p className="font-medium">{config.metadata.name}</p>
                  </div>
                  <div>
                    <Label className="text-muted-foreground text-xs">Version</Label>
                    <p className="font-medium">{config.version}</p>
                  </div>
                  <div>
                    <Label className="text-muted-foreground text-xs">Author</Label>
                    <p className="font-medium">{config.metadata.author}</p>
                  </div>
                  <div>
                    <Label className="text-muted-foreground text-xs">Last Updated</Label>
                    <p className="font-medium text-xs font-mono">
                      {new Date(config.metadata.lastUpdated).toLocaleString()}
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Tokens File */}
            <Card>
              <CardHeader className="pb-3">
                <div className="flex items-center justify-between">
                  <CardTitle className="text-sm font-semibold">tokens.ts</CardTitle>
                  <div className="flex gap-2">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleCopy(tokensExport, 'tokens')}
                      className="transition-all hover:scale-105"
                    >
                      {copiedFile === 'tokens' ? (
                        <Check className="w-4 h-4 mr-2" />
                      ) : (
                        <Copy className="w-4 h-4 mr-2" />
                      )}
                      Copy
                    </Button>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleDownload(tokensExport, 'tokens.ts')}
                      className="transition-all hover:scale-105"
                    >
                      <Download className="w-4 h-4 mr-2" />
                      Download
                    </Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <pre className="bg-muted p-3 rounded-md overflow-x-auto text-xs font-mono max-h-48">
                  {tokensExport}
                </pre>
              </CardContent>
            </Card>

            {/* Themes File */}
            <Card>
              <CardHeader className="pb-3">
                <div className="flex items-center justify-between">
                  <CardTitle className="text-sm font-semibold">themes.ts</CardTitle>
                  <div className="flex gap-2">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleCopy(themesExport, 'themes')}
                      className="transition-all hover:scale-105"
                    >
                      {copiedFile === 'themes' ? (
                        <Check className="w-4 h-4 mr-2" />
                      ) : (
                        <Copy className="w-4 h-4 mr-2" />
                      )}
                      Copy
                    </Button>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleDownload(themesExport, 'themes.ts')}
                      className="transition-all hover:scale-105"
                    >
                      <Download className="w-4 h-4 mr-2" />
                      Download
                    </Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <pre className="bg-muted p-3 rounded-md overflow-x-auto text-xs font-mono max-h-48">
                  {themesExport}
                </pre>
              </CardContent>
            </Card>

            {/* Instructions */}
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-semibold">How to Use</CardTitle>
              </CardHeader>
              <CardContent className="space-y-2 text-sm">
                <p className="text-muted-foreground">
                  <strong className="text-foreground">1.</strong> Download or copy the files above
                </p>
                <p className="text-muted-foreground">
                  <strong className="text-foreground">2.</strong> Replace files in your mobile app:
                </p>
                <code className="block bg-muted p-2 rounded text-xs font-mono">
                  mobile/src/framework/design/tokens.ts<br />
                  mobile/src/framework/design/themes.ts
                </code>
                <p className="text-muted-foreground">
                  <strong className="text-foreground">3.</strong> Rebuild your app
                </p>
              </CardContent>
            </Card>
          </div>
        </ScrollArea>

        <div className="p-6 border-t flex justify-end gap-2 shrink-0 bg-background">
          <Button variant="outline" onClick={onClose} className="transition-all hover:scale-105">
            Close
          </Button>
          <Button onClick={() => {
            handleDownload(tokensExport, 'tokens.ts');
            handleDownload(themesExport, 'themes.ts');
          }} className="transition-all hover:scale-105">
            <Download className="w-4 h-4 mr-2" />
            Download All
          </Button>
        </div>
      </div>
    </div>
  );
}
