/**
 * Design Tokens - Core values for the design system
 * These tokens are generated by the Web Builder and can be hot-reloaded
 */

import type { Tokens } from './types';

export const tokens: Tokens = {
  color: {
    primary: { value: '#ec1334', type: 'color', description: 'Primary brand color' },
    primaryDeep: { value: '#9f1239', type: 'color', description: 'Deep primary for hover states' },
    primarySoft: { value: '#ffe4e6', type: 'color', description: 'Soft primary for backgrounds' },
    accent: { value: '#2563eb', type: 'color', description: 'Accent color for highlights' },
    secondary: { value: '#7B61FF', type: 'color', description: 'Secondary brand color' },
    
    // Neutrals
    ink: { value: '#0f172a', type: 'color', description: 'Darkest text color' },
    muted: { value: '#64748b', type: 'color', description: 'Muted text color' },
    white: { value: '#ffffff', type: 'color', description: 'Pure white' },
    black: { value: '#000000', type: 'color', description: 'Pure black' },
    
    // Slates
    slate: {
      '50': { value: '#f8fafc', type: 'color' },
      '100': { value: '#f1f5f9', type: 'color' },
      '200': { value: '#e2e8f0', type: 'color' },
      '300': { value: '#cbd5e1', type: 'color' },
      '400': { value: '#94a3b8', type: 'color' },
      '500': { value: '#64748b', type: 'color' },
      '600': { value: '#475569', type: 'color' },
      '700': { value: '#334155', type: 'color' },
      '800': { value: '#1e293b', type: 'color' },
      '900': { value: '#0f172a', type: 'color' },
    },
    
    // Semantic
    semantic: {
      danger: { value: '#ef4444', type: 'color', description: 'Error and destructive actions' },
      success: { value: '#10b981', type: 'color', description: 'Success states' },
      warning: { value: '#f59e0b', type: 'color', description: 'Warning states' },
      info: { value: '#3b82f6', type: 'color', description: 'Informational states' },
    },
    
    // Glassmorphism
    glass: {
      glass: { value: 'rgba(255, 255, 255, 0.4)', type: 'color', description: 'Glass effect background' },
      glassStrong: { value: 'rgba(255, 255, 255, 0.6)', type: 'color', description: 'Strong glass effect' },
      glassBorder: { value: 'rgba(255, 255, 255, 0.5)', type: 'color', description: 'Glass border color' },
    },
  },
  
  space: {
    none: { value: 0, type: 'spacing', description: 'No spacing' },
    '3xs': { value: 2, type: 'spacing' },
    '2xs': { value: 4, type: 'spacing' },
    xs: { value: 8, type: 'spacing' },
    sm: { value: 12, type: 'spacing' },
    md: { value: 16, type: 'spacing', description: 'Default spacing unit' },
    lg: { value: 24, type: 'spacing' },
    xl: { value: 32, type: 'spacing' },
    '2xl': { value: 40, type: 'spacing' },
    '3xl': { value: 48, type: 'spacing' },
    '4xl': { value: 64, type: 'spacing' },
    true: { value: 16, type: 'spacing', description: 'Default spacing' },
  },
  
  size: {
    xs: { value: 28, type: 'size' },
    sm: { value: 36, type: 'size' },
    md: { value: 44, type: 'size', description: 'Default control height' },
    lg: { value: 52, type: 'size' },
    xl: { value: 64, type: 'size' },
    true: { value: 44, type: 'size', description: 'Default size' },
  },
  
  radius: {
    none: { value: 0, type: 'borderRadius', description: 'Square corners' },
    xs: { value: 4, type: 'borderRadius' },
    sm: { value: 8, type: 'borderRadius' },
    md: { value: 12, type: 'borderRadius' },
    lg: { value: 18, type: 'borderRadius' },
    xl: { value: 24, type: 'borderRadius' },
    '2xl': { value: 32, type: 'borderRadius' },
    pill: { value: 9999, type: 'borderRadius', description: 'Fully rounded pill shape' },
  },
  
  zIndex: {
    true: { value: 1, type: 'zIndex', description: 'Default z-index' },
    toast: { value: 999999, type: 'zIndex', description: 'Toast notifications' },
    modal: { value: 1000, type: 'zIndex', description: 'Modal overlays' },
  },
  
  typography: {
    fontFamily: {
      heading: { value: 'BeVietnamPro_700Bold', type: 'fontFamily', description: 'Heading font family' },
      body: { value: 'BeVietnamPro_400Regular', type: 'fontFamily', description: 'Body text font family' },
      mono: { value: 'RobotoMono_400Regular', type: 'fontFamily', description: 'Monospace font for code' },
    },
    fontSize: {
      '1': { value: 12, type: 'fontSize' },
      '2': { value: 14, type: 'fontSize' },
      '3': { value: 16, type: 'fontSize' },
      '4': { value: 18, type: 'fontSize' },
      '5': { value: 22, type: 'fontSize' },
      '6': { value: 28, type: 'fontSize' },
      '7': { value: 34, type: 'fontSize' },
    },
    lineHeight: {
      '1': { value: 16, type: 'lineHeight' },
      '2': { value: 20, type: 'lineHeight' },
      '3': { value: 24, type: 'lineHeight' },
      '4': { value: 26, type: 'lineHeight' },
      '5': { value: 30, type: 'lineHeight' },
      '6': { value: 36, type: 'lineHeight' },
      '7': { value: 42, type: 'lineHeight' },
    },
    fontWeight: {
      regular: { value: '400', type: 'fontWeight' },
      medium: { value: '500', type: 'fontWeight' },
      semiBold: { value: '600', type: 'fontWeight' },
      bold: { value: '700', type: 'fontWeight' },
      extraBold: { value: '800', type: 'fontWeight' },
    },
  },
  
  shadow: {
    sm: { 
      value: { offsetX: 0, offsetY: 1, blur: 2, color: 'rgba(0, 0, 0, 0.05)' },
      type: 'shadow',
      description: 'Small shadow for subtle elevation'
    },
    md: { 
      value: { offsetX: 0, offsetY: 4, blur: 6, color: 'rgba(0, 0, 0, 0.1)' },
      type: 'shadow',
      description: 'Medium shadow for cards'
    },
    lg: { 
      value: { offsetX: 0, offsetY: 10, blur: 15, color: 'rgba(0, 0, 0, 0.1)' },
      type: 'shadow',
      description: 'Large shadow for modals'
    },
    xl: { 
      value: { offsetX: 0, offsetY: 20, blur: 25, color: 'rgba(0, 0, 0, 0.15)' },
      type: 'shadow',
      description: 'Extra large shadow'
    },
    '2xl': { 
      value: { offsetX: 0, offsetY: 25, blur: 50, color: 'rgba(0, 0, 0, 0.25)' },
      type: 'shadow',
      description: 'Largest shadow for dramatic elevation'
    },
    inner: { 
      value: { offsetX: 0, offsetY: 2, blur: 4, color: 'rgba(0, 0, 0, 0.06)' },
      type: 'shadow',
      description: 'Inner shadow for inset effect'
    },
  },
  
  breakpoint: {
    sm: { value: '640px', type: 'breakpoint', description: 'Small devices' },
    md: { value: '768px', type: 'breakpoint', description: 'Medium devices' },
    lg: { value: '1024px', type: 'breakpoint', description: 'Large devices' },
    xl: { value: '1280px', type: 'breakpoint', description: 'Extra large devices' },
    '2xl': { value: '1536px', type: 'breakpoint', description: 'Largest devices' },
  },
};
